### PR TITLE
Fix velocity unit

### PR DESCRIPTION
**Pull request by tjjarvinen**
As a response to this https://github.com/JuliaMolSim/JuLIP.jl/pull/160#issuecomment-1410403009

ASE units defined in [here](https://wiki.fysik.dtu.dk/ase/ase/units.html) state that _"Electron volts (eV), Ångström (Ang), the atomic mass unit and Kelvin are defined as 1.0."_

Energy has dimensions of "M*L^2/T^2" or mass times velocity squared. From this you can deduce that square root of energy divided by square root of mass gives the unit of velocity, or using Unitful terms `u"eV^0.5/u^0.5"`.

I am not completely sure that this is the correct velocity unit... But this is how I understood it.

### CODE REVIEW

**Comment by mfherbst** [comment]
@jameskermode Can you confirm?

**Comment by mfherbst** [comment]
@tjjarvinen Thanks for this PR. This unit business is always super subtle. In the end that's the reason we opted for sticking the units on in AtomsBase by default.

**Comment by mfherbst** [comment]
@tjjarvinen Needed a bit more refactoring as it turned out doing the testing system in absolute tolerances is not the best idea. I had no clue about the range of Angstrom per second in atomic units. It's super tiny! So the tests were effectively testing nothing.

**Comment by mfherbst** [comment]
@jameskermode  I think I understand the ASE docs now. If you have a second, just confirm what we did makes sense now.

**Comment by jameskermode** [comment]
Yes, this looks correct to me

**Pull request merged**
